### PR TITLE
Tools.analyzer ast

### PR DESCRIPTION
**Pull request by AnOctopus**
These were the two easy changes for reducing the number of impl-case uses.

### CODE REVIEW

**Comment by frenchy64** [comment]
Just eye balling it atm -- do the CLJS tests pass?

**Comment by AnOctopus** [comment]
The leiningen tests pass, the tests against the 4 JS engines fail in the same way that the branch fails. I'll fix it.

**Comment by AnOctopus** [comment]
I've been working through some of the issues that come up when running the tests with the actual JS runtimes, and have fixed most of the regressions I could find. 

I'm currently stuck on an odd issue where, when using defmethod multiple times with a dispatch value of a vector of any particular length, the arr field of the iterator used in the vector equality comparison is undefined. The JS stacktrace is, at this point, calling identical javascript as it does in the (working) commit before it. I don't see any plausible changes that would affect any of this, so I have some tedious change bisection to do, after maybe getting the test case a bit more minimal.

**Comment by frenchy64** [comment]
I noted these changes in https://dev.clojure.org/jira/browse/CLJS-1461 and I'm closing this since the master branch has diverged so drastically.

**Pull request closed without merging**
